### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by AffectAge** [AustereTony-MCMods/Oxygen-Currency-Providers#1]
Coremod CurrencyProviderCorePlugin: Unable to class load the plugin austeretony.oxygen_cp_ge.common.core.CurrencyProviderCorePlugin
 java.lang.ClassNotFoundException: austeretony.oxygen_cp_ge.common.core.CurrencyProviderCorePlugin
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:127) ~[MohistServer.jar:d3c98c9]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) [MohistServer.jar:d3c98c9]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) [MohistServer.jar:d3c98c9]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [MohistServer.jar:d3c98c9]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:108) [MohistServer.jar:d3c98c9]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:88) [MohistServer.jar:d3c98c9]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) [MohistServer.jar:d3c98c9]
        at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) [MohistServer.jar:d3c98c9]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:113) [MohistServer.jar:d3c98c9]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:26) [MohistServer.jar:d3c98c9]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at red.mohist.Mohist.main(Mohist.java:92) [MohistServer.jar:d3c98c9]
[latest.log](https://github.com/AustereTony-MCMods/Oxygen-Currency-Providers/files/4236657/latest.log)

**Comment by TheKlimoT** [comment]
+1

**Comment by AustereTony-MCMods** [comment]
Thanks for the report.

This is an error in building the mod file, it is completely safe. It will be fixed in version 0.11.
